Fix forge pr checkout for AGit-flow
I encountered this error:

```
$ git cd https://codeberg.org/forgejo/website/pulls/926/files
fatal: couldn't find remote ref refs/heads/refs/pull/926/head
Error: fetching origin/refs/pull/926/head: exit status 128
```

It turned out that the gitea module returns a full git ref
`refs/pull/123` for PRs that don't have a real git branch to check out
to.

This case wasn't properly handled by the generic checkout code.